---
- name: Set Ip Address
  hosts: all
  gather_facts: no

  tasks: 
    - name: Set IPv4 address eth0/0
      ios_l3_interface:
        name: ethernet0/0
        ipv4: 192.168.1.2/24   
    - name: no shut
      ios_l3_interface:
        name: ethernet0/0
        state: present

    - name: Show ip 
      ios_command:
        commands: 
          - show ip int brief
      register: show_ip

    - debug:
        var: show_ip.stdout_lines