---
- name: Router1
  hosts: cisco 
  connection: local
  gather_facts: false

  tasks: 
    - name: get base information 
      ios_command:
        commands: 
          - show version | include IOS
          - show ip int brief

      register: print_output

    - debug:
        var: print_output.stdout_lines