--- 
- name: Set IP DCHP
  hosts: cisco
  connection: network_cli
  gather_facts: false

  tasks: 
    - name: Set ethernet0/1 IPv4 Address  
      ios_config:
        parents:
          - interface ethernet0/1
        lines: 
          - no shut 

    - name: Config Sub-interface e0/1.10
      ios_config:
        parents:
          - interface e0/1.10
        lines: 
          - description dai cho vlan 10
          - encapsulation dot1q 10
          - ip address 192.168.10.1 255.255.255.0 

    - name: Config Sub-interface e0/1.20 
      ios_config: 
        parents:
          - interface e0/1.20 
        lines: 
          - description dai cho vlan 20
          - encapsulation dot1q 20
          - ip address 192.168.20.1 255.255.255.0 
  

    - name: Config Sub-interface e0/1.30
      ios_config:
        parents: 
          - interface ethernet0/1.30
        lines: 
          - description dai cho vlan 30
          - encapsulation dot1q 30 
          - ip address 192.168.30.1 255.255.255.0 

    - name: Set DHCP e0/1.10
      ios_config:
        parents:
          - ip dhcp pool LAN_10 
        lines:
          - network 192.168.10.0 /24 
          - default-router 192.168.10.1 
          - dns-server 8.8.8.8 

    - name: Set DHCP e0/1.20
      ios_config:
        parents:
          - ip dhcp pool LAN_20 
        lines:
          - network 192.168.20.0 /24 
          - default-router 192.168.20.1 
          - dns-server 8.8.8.8
    
    - name: Set DHCP e0/1.30 
      ios_config: 
        parents:
          - ip dhcp pool LAN_30 
        lines:
          - network 192.168.30.0 /24 
          - default-router 192.168.30.1 
          - dns-server 8.8.8.8
    
    - name: show ip
      ios_command:
        commands:
          - sh run
          - sh ip dhcp binding 
      
      register: show_ip   # gắn kết quả vào biến show_ip
    
    - debug: var=show_ip.stdout_lines
      
