--- 
- name: Config router 
  hosts: routers  
  connection: network_cli
  gather_facts: false

  tasks: 
    - name: Set ip cho cổng e0/1
      ios_l3_interface:
        name: ethernet0/1
        ipv4: 192.168.1.1/24
        
    - name: Set subint 
      ios_config:
        parents:
          - int {{ item.subint }}
        lines:
          - encapsulation dot1q {{ item.vlan }}
          - ip address 192.168.{{ item.vlan }}.1 255.255.255.0
      with_items: 
        - { subint: ethernet0/1.10, vlan: 10 }
        - { subint: ethernet0/1.20, vlan: 20 }
        - { subint: ethernet0/1.30, vlan: 30 }
              
    - name: show ip
      ios_command:
        commands:
          - sh ip int bri
      
#cách 1
    - name: Config DHCP
      ios_config:
        parents:
          - ip dhcp pool {{item.name}}
        lines:
          - network 192.168.{{item.vlan}}.0 255.255.255.0
          - default-router 192.168.{{item.vlan}}.1
          - dns-server 8.8.8.8
      with_items:
          - name: LAN_10
            vlan: 10
          - name: LAN_20
            vlan: 20
          - name: LAN_30
            vlan: 30
                  
    
- name: Config switch 
  hosts: Switch 
  connection: network_cli 
  gather_facts: false 
    
  tasks: 
    - name: create vlan
      ios_vlan: 
        aggregate: 
          - { vlan_id: 10 }
          - { vlan_id: 20 }
          - { vlan_id: 30 }
    
    - name: gan cong vao vlan 
      ios_l2_interface: 
        name: " {{ item.int }} "
        mode: access 
        access_vlan: "{{ item.vlan }}"
      with_items:
        - { vlan: "10", int: "ethernete0/2.10"}
        - { vlan: "20", int: "ethernete0/2.20"}
        - { vlan: "30", int: "ethernete0/2.30"}

    - name: Cong e0/1 sang mode trunk
      ios_config: 
        parents: 
          - int e0/1 
        lines:
          - switchport trunk encapsulation dot1q 
          - switchport mode trunk      


      register: show_ip 

    - debug: var=show_ip.stdout_lines


          


        


