---
- name: Config BR_HCM1
  hosts: BR_HCM1 
  connection: network_cli
  gather_facts: false 

  tasks: 
    - name: Set IP on interface e0/1 
      ios_config: 
        parents:
          - interface e0/1 
        lines:
          - no shut
          - ip address 192.168.3.9 255.255.255.248
          - ip nat inside  
          - ip ospf 1 area 3
    
    - name: Set IP on interface e0/2
      ios_config: 
        parents:
          - interface e0/2
        lines:
          - no shut
          - ip address 192.168.3.1 255.255.255.248
          - ip nat inside
          - ip ospf 1 area 3
    
    - name: Set IP on interface e0/3 
      ios_config: 
        parents:
          - interface e0/3
        lines:
          - no shut
          - ip address 10.10.3.2 255.255.255.0
          - ip nat outside

    - name: Config OSPF with Process ID 1
      ios_config:
        parents:
          - router ospf 1 
        lines:
          - redistribute static subnets 
          - default-information originate

    - name: Config tunnel 0
      ios_config:
        parents:
          - interface Tunnel0
        lines:
          - ip address 172.16.0.1 255.255.255.252
          - tunnel mode gre ip
          - tunnel source 10.10.3.2
          - tunnel destination 10.10.1.2
    
    - name: Config tunnel 1
      ios_config: 
        parents:
          - interface Tunnel1
        lines:
          - ip address 172.16.1.1 255.255.255.252
          - tunnel mode gre ip
          - tunnel source 10.10.3.2
          - tunnel destination 10.10.2.2

    - name: Static route 
      ios_config:
        lines: 
          - access-list 3 permit any
          - ip nat inside source list 3 interface Ethernet0/3 overload
          - ip route 0.0.0.0 0.0.0.0 10.10.3.1
          - ip route 192.168.1.0 255.255.255.0 172.16.0.2 120
          - ip route 192.168.2.0 255.255.255.0 172.16.1.2 120



- name: Config BR_HCM2
  hosts: BR_HCM2 
  connection: network_cli
  gather_facts: false 

  tasks: 
    - name: Set IP on interface e0/1 
      ios_config: 
        parents:
          - interface e0/1 
        lines:
          - no shut
          - ip address 192.168.3.17 255.255.255.248
          - ip ospf 1 area 3
    
    - name: Set IP on interface e0/2
      ios_config: 
        parents:
          - interface e0/2
        lines:
          - no shut
          - ip address 172.16.123.3 255.255.255.0
          - ip ospf 1 area 0
    
    - name: Set IP on interface e0/3 
      ios_config: 
        parents:
          - interface e0/3
        lines:
          - no shut
          - ip address 192.168.3.2 255.255.255.248
          - ip ospf 1 area 3

    - name: Config OSPF with Process ID 1
      ios_config:
        lines:
          - router ospf 1 
        


- name: Config on SW_HCM
  hosts: SW_HCM
  connection: network_cli
  gather_facts: false 

  tasks: 
    - name: Set IP on interface e0/1 
      ios_config: 
        parents: 
          - interface e0/1 
        lines:
          - no switchport
          - ip address  192.168.3.10 255.255.255.248 
          - ip ospf 1 area 3

    - name: Set IP on interface e0/2
      ios_config: 
        parents: 
          - interface e0/2
        lines:
          - no switchport
          - ip address  192.168.3.18 255.255.255.248
          - ip ospf 1 area 3

    - name: ACCESS VLAN
      ios_l2_interface:
        name: " {{ item.int}}"
        mode: access 
        access_vlan: " {{ item.vlan}}"
      with_items: 
        - { int: "ethernet0/3", vlan: 30}
        - { int: "ethernet1/0", vlan: 40}

    - name: Config DHCP on SW_HCM 
      ios_config: 
        parents:
          - ip dhcp pool {{ item.name }}
        lines:
          - network 10.0.{{item.vlan}}.0 255.255.255.0 
          - default-router 10.0.{{item.vlan}}.1
      with_items:
        - { name: "LAN_30", vlan: 0}
        - { name: "LAN_40", vlan: 1}

    - name: Config OSPF with Process ID 1
      ios_config:
        parents:
          - router ospf 1 
        lines:
          - redistribute connected subnets 